version: "3.7"

services:
  db:
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pgweb:
    image: sosedoff/pgweb:0.11.5
    restart: always
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable

volumes:
  db_data:
